### ISSUE TITLE
Journal Entries are White background with White Text, Impossible to read.

### ISSUE THREAD

**Issue by Aceman67** [FabulistVtt/sta-lcars-ui#1]
![Screenshot 2022-09-04 180448](https://user-images.githubusercontent.com/52718032/188338741-1b4e2995-6689-450a-9b4a-f86ca170cbbf.png)
Journal Entries are White background with White Text, Impossible to read.
How do I change this?

**Comment by FabulistVtt** [comment]
Fixed with v0.3.0.
